### ISSUE TITLE
Games Settings 

### ISSUE THREAD

**Issue by mapi68** [wyrm65/skin.apptv#24]
**Describe the bug**
In english in menu Settings "Games Settings" has "S" uppercase;
in italian in menu Settings "Games Settings" has reversed words and uppercase.

**To Reproduce**
Go to 'Settings...' or "Impostazioni...".

**Expected behavior**
In english "Games settings";
in italian "Impostazioni giochi".

**Desktop:**
 - OS: all
 - Kodi: Nexus 22

**Screenshots**

![2023-02-26_100049](https://user-images.githubusercontent.com/41143572/221402338-4abec032-d7d0-46a6-8169-8170d22c0ae0.png)
![2023-02-26_100351](https://user-images.githubusercontent.com/41143572/221402340-08679e5d-3b0c-426a-b7ca-5cd1ff2ef87c.png)

**Comment by wyrm65** [comment]
Sorry don’t know Italian so translations are provided by Weblate. Not sure why that string was translated in that manner, looking at it I would agree that your way makes more sense.

Now the other problem would be that is not a skin string (provided by AppTV) but a Kodi string. Sorry but issue lies with Kodi and needs to be fixed by them.

To confirm that it is a Kodi issue, change to another skin (use the default skin provided by Kodi) and see if the heading if different to that provided by my skin. If it’s shown the same it’s a Kodi problem and you need to bring it the developer’s attention. 

Sorry could not help your more, but out of my control.

Wyrm

**Comment by mapi68** [comment]
I know very well Kodi in Italian because I have translated more than 22'000 strings (program, add-on, skin, ALL!) but this settings screen doesn't exist anywhere.

**Comment by mapi68** [comment]
The problem is line 99 in https://github.com/wyrm65/skin.apptv/blob/master/xml/Settings.xml that has two LOCALIZE reference: 15016 for Games and 5 for Settings, but it's not correct neither in English neither in all languages. I think the best solution is remove lines 98, 99, 100, 101.

**Comment by mapi68** [comment]
Another issue: last lline "Event Log" has no correct LOCALIZE (line 123 of https://github.com/wyrm65/skin.apptv/blob/master/xml/Settings.xml must be 10050 instead of 31658).
After you have:
![2023-02-26_173308](https://user-images.githubusercontent.com/41143572/221423852-30ff3e3f-06b2-4c39-a227-4c0788f85ab0.png)

**Comment by wyrm65** [comment]
Issues fixed in my last two pulls. See your PR for details (your pull has also been closed as no longer required).

Many thanks for bringing the issue to my attention.

Wyrm
